### ISSUE TITLE
Switch over production 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#57]
@randomorder @lpasquali 
please list here all activities/steps to consider for the switch in production to the new SDI.

- [x] Tuning of the VH/Reverse Proxy to point to the new SDI (@lpasquali assist Francesco F.)
   - datigis.comune.fi.it 
   - datigis.comune.intranet
   - datigis2.comune.fi.it
   - datigis2.comune.intranet
   - mapstore2.comune.fi.it
   - tms.comune.fi.it, tms2.comune.fi.it, tms3.comune.fi.it, tms4.comune.fi.it
   - tms.comune.intranet, tms1.comune.intranet, tms2.comune.intranet, tms3.comune.intranet, tms4.comune.intranet
   - tmsurb.comune.intranet, tmsurb1.comune.intranet, tmsurb2.comune.intranet, tmsurb3.comune.intranet, tmsurb4.comune.intranet
- [x] Activate new Kibana configurations to point to the new SDI (#56) @lpasquali  
- [x] New test tour before going live @ElenaGallo 
- [x] Complete the deployment and administration documentation for the client (#55) @lpasquali @randomorder 

**The new SDI will be moved in prod on 04-04-2022**

**_GeoSolutions need user account to access the SITPUB server to be able to work on VHs (still waiting the client for this)._**

**Comment by lpasquali** [comment]
@tdipisa @randomorder kibana is working and indexing new servers logs and audit, see my comments about what should be done furtherly here: https://github.com/geosolutions-it/MapStore2-C027/issues/56
I'm finishing documentation

**Comment by lpasquali** [comment]
@tdipisa @randomorderI report here the two issues of this morning:

one from Francesca Corti on layer :
http://sr-vm380-sitgs1:8080/geoserver/wms?service=WMS&version=1.1.0&request=GetMap&layers=servizi_web:centro_storico_unesco&bbox=1680007.27964785%2C4847443.17661007%2C1682857.18868568%2C4850370.9302293&width=747&height=768&srs=EPSG%3A3003&styles=&format=application/openlayers

Risposta: java.lang.RuntimeException: Error getting FeatureType, this should never happen!
Error getting FeatureType, this should never happen!
Error occurred building feature type
ORA-00942: table or view does not exist

this has been fixed, there were two stores with same layer, removing the layer on oracle (dismissed) the problem solved.

There is alro another issue reported by MArrassini about a shapefile which was only possible to be downloaded from slave1
on slave2 it gave no such file or directory.
on master it downloaded the shapefile correctly, 
restarting slave 2  solved the issue, and it is possible that the cause was this scenario:
- user edits master - reloads
- user edits one slave - reloads
- user forgot to edit slave 2.
The problem for so was due to a misuse of alignment procedure between slaves and master. from my analysis

**Comment by tdipisa** [comment]
@lpasquali 
>restarting slave 2  solved the issue, and it is possible that the cause was this scenario:
- user edits master - reloads
- user edits one slave - reloads
- user forgot to edit slave 2.
The problem for so was due to a misuse of alignment procedure between slaves and master. from my analysis

We have to possibly report this. We have to ensure the client use the synch script for the data directory without doing edits on each node separately.

**Comment by lpasquali** [comment]
@tdipisa @randomorder there was a not working rewrite for mapstore that I fixed:
http://mapstore2.comune.fi.it/  -> http://mapstore2.comune.fi.it/ mapstore2

**Comment by randomorder** [comment]
thanks. My understanding is there are no pending actions on Ops at this point in time. For any new request please add an issue to this epic @lpasquali
